package com.sample.rules

import com.sample.*

rule "Looking For Non-Default"
    when
        $class: ClassImplementingInterfaceWithDefaults( val: notDefaultString )
    then
        System.out.println("Looking For Non-Default: " + val);
end

rule "Looking For Default"
    when
        $class: ClassImplementingInterfaceWithDefaults( val: defaultString )
    then
        System.out.println("Looking For Default: " + val);
end

rule "Looking For Overwritten Default"
    when
        $class: ClassImplementingInterfaceWithDefaultsAndOverwritingDefault( val: defaultString )
    then
        System.out.println("Looking For Overwritten Default: " + val);
end
